dbstop if error
format compact
close all
clear
clc

%% Part 1
theta_dot = [.2, -.2, 10];
delta_v_d = [0, -1.2, 0];
cost = myPrinter1(theta_dot, delta_v_d, 1, 0)
cost_no_elec = myPrinter1(theta_dot, delta_v_d, 1, 1)

%% Part 2
dbstop if error
format compact
close all
clear
clc

children = 10; % number of designs generated by breeding
parents = 10; % number of designs kept from last generation
S = 100; % designs per generation
G = 100; % max number of generations
dv = 4;
TOL_GA = 2e-2;
interval = [
    15,16;
    15,16;
    6,7;
    -3.5,-3];
%     theta_dot = [.2, -.2, 10];
%     delta_v_d = [0, -1.2, 0];
myPrinter2_GA = @(theta_dot_1, theta_dot_2, theta_dot3, delta_v_d_y) myPrinter2([theta_dot_1, theta_dot_2, theta_dot3], [0, delta_v_d_y, 0], 0);
%     cost = myPrinter2(theta_dot, delta_v_d)
t0 = tic;
[PI, Orig, Lambda, bd] =  myGenetic(myPrinter2_GA, interval, parents, TOL_GA, G, S, dv);
toc(t0);
bd
% comparepattern(bd(1), bd(2), bd(3), bd(4))
myPrinter2([bd(1), bd(2), bd(3)], [0, bd(4), 0], 1)

for i = 1:4
    fprintf("%d & ", i);
    fprintf("%.3f & ", PI(G, i))
    for j = 1:dv
        if j == dv
            fprintf("%.3f %s\n", Lambda(i, j), '\\')
        else
            fprintf("%.3f & ", Lambda(i, j))
        end
    end
    fprintf("\n")
end

%%
figure;
bd_over_time = PI(:,1);
plot(bd_over_time)
hold on
parents_over_time = mean(PI(:,1:10), 2);
plot(parents_over_time)
pop_over_time = mean(PI, 2);
plot(pop_over_time)
xlabel('Generation')
ylabel('Cost')
legend('Best Design', 'Average Parents', 'Average Population')
hold off
