close all
clear
clc

dbstop if error
format compact

% From Table 1
dt = .2; % s. time step size
t_f = 60; % s. maximum task time
time_steps = 0:dt:t_f; % time step iterator
num_steps = length(time_steps); % time_step index iterator



% From Table 3
children = 6; % number of designs generated by breeding
parents = 6; % number of designs kept from last generation
S = 20; % designs per generation
G = 100; % max number of generations
dv = 15;

% initial positions of agents
% each col is the position of the ith agent
N_m = 15; % number of initial agents
r_i(1, :) = [-110, -110, -110, -110, -110, -120, -120, -120, -120, -120, -130, -130, -130, -130, -130];
r_i(2, :) = linspace(-10, 10, N_m);
r_i(3, :) = linspace(-10, 10, N_m);

% initial positions of obstacles
% each col is the position of the jth obstacle
N_o = 25;
O_j(1:2, :) = -100 + 200 .* rand(2, N_o);
O_j(3, :) = -10 + 20 .* rand(1, N_o);
% O_j(1, :) = linspace(-100, 100, N_o);
% O_j(2, :) = linspace(-100, 100, N_o);
% O_j(3, :) = linspace(-10, 10, N_o);

% initial positions of targets
% each col is the position of the jth target
N_t = 100;
T_j(1:2, :) = -100 + 200 .* rand(2, N_t);
T_j(3, :) = -10 + 20 .* rand(1, N_t);
% T_j(1, :) = linspace(-100, 100, N_t);
% T_j(2, :) = linspace(-100, 100, N_t);
% T_j(3, :) = linspace(-10, 10, N_t);


%% Testing
% Create function with all initial conditions passed
uav_func = @(W_mt, W_mo, W_mm, w_t1, w_t2, w_o1, w_o2, w_m1, w_m2, a_1, a_2, b_1, b_2, c_1, c_2) myUAV(0, N_m, N_t, N_o, r_i, O_j, T_j, W_mt, W_mo, W_mm, w_t1, w_t2, w_o1, w_o2, w_m1, w_m2, a_1, a_2, b_1, b_2, c_1, c_2);

% [cost] = uav_func(W_mt, W_mo, W_mm, w_t1, w_t2, w_o1, w_o2, w_m1, w_m2, a_1, a_2, b_1, b_2, c_1, c_2)
t0 = tic;
[PI, Orig, Lambda, bd, Tstars, Lstars, Mstars] = myGenetic(uav_func, [0, 2], parents, G, S, dv);
toc(t0);

%% SAVE
% save("vars1")

%% Plot and cost check
% bd = [1.1661    0.2426    1.8556    1.7055    0.7839    0.2028    0.9604    1.2869    1.7900    0.1744    0.5371    0.4155    1.3240 0.8848    0.6899];
bd = Lambda(1, :)
uav_func = @(W_mt, W_mo, W_mm, w_t1, w_t2, w_o1, w_o2, w_m1, w_m2, a_1, a_2, b_1, b_2, c_1, c_2) myUAV(1, N_m, N_t, N_o, r_i, O_j, T_j, W_mt, W_mo, W_mm, w_t1, w_t2, w_o1, w_o2, w_m1, w_m2, a_1, a_2, b_1, b_2, c_1, c_2);
[cost, Tstar, Lstar, Mstar] = uav_func(bd(1), bd(2), bd(3), bd(4), bd(5), bd(6), bd(7), bd(8), bd(9), bd(10), bd(11), bd(12), bd(13), bd(14), bd(15))

%% Report stuff 1
close all
clc

best_designs = Lambda(1:4, :);

best_costs = PI(:, 1);
figure;
plot(best_costs)
hold on
mean_parents = mean(PI(:, 1:parents), 2);
plot(mean_parents)
mean_all = mean(PI, 2);
plot(mean_all)
legend('Best Design Cost', 'Mean Parent Cost', 'Mean Population Cost')
% title('Various Costs vs. Generation')
xlabel('Generation')
ylabel('Weighted Cost')

for i = 1:4
    fprintf("%d & ", i);
    fprintf("%.3f & ", PI(100, i))
    for j = 1:15
        fprintf("%.3f & ", Lambda(i, j))
    end
    fprintf("\n")
end

%% Report stuff 2a
close all
clc

figure;

best_mstars = Mstars(:, 1);
best_tstars = Tstars(:, 1);
best_lstars = Lstars(:, 1);

plot(best_mstars)
hold on
plot(best_tstars)
plot(best_lstars)
legend("w_1M*", "w_2T*", "w_3L*")
xlabel("Generation")
ylabel("Weighted Cost Component")

%% 2b
close all
figure;
par_mstar = mean(Mstars(:, 1:parents), 2);
par_tstar = mean(Tstars(:, 1:parents), 2);
par_lstar = mean(Lstars(:, 1:parents), 2);

plot(par_mstar)
hold on
plot(par_tstar)
plot(par_lstar)
legend("w_1M*", "w_2T*", "w_3L*")
xlabel("Generation")
ylabel("Weighted Cost Component")

%% 2c
close all
figure;
all_mstar = mean(Mstars, 2);
all_tstar = mean(Tstars, 2);
all_lstar = mean(Lstars, 2);

plot(all_mstar)
hold on
plot(all_tstar)
plot(all_lstar)
legend("w_1M*", "w_2T*", "w_3L*")
xlabel("Generation")
ylabel("Weighted Cost Component")
